name: authentication_repository
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  firebase_auth: 3.0.2
  firebase_core: 1.13.1
  flutter:
    sdk: flutter
  cache:
    git:
      url: https://github.com/tyler-jewell/cache.git
      ref: main
  google_sign_in: ^5.4.0
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
